# Generated by Django 4.2 on 2023-04-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_inbound', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('inbound_date', models.DateField(auto_now_add=True)),
                ('price_inbound', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
            ],
            options={
                'db_table': 'inbound',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
            ],
            options={
                'db_table': 'my_products',
            },
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_outbound', models.CharField(max_length=20)),
                ('quantity_outbound', models.IntegerField(default=0)),
                ('date_outbound', models.DateField(auto_now_add=True)),
                ('price_outbound', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('item_outbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.product')),
            ],
            options={
                'db_table': 'outbound',
            },
        ),
    ]
