# Generated by Django 4.2 on 2023-04-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbound',
            name='item_outbound',
        ),
    ]
