# Generated by Django 4.2 on 2023-04-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_inbound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='product',
        ),
        migrations.AddField(
            model_name='inbound',
            name='code_inbound',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inbound',
            name='price_inbound',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
