# Generated by Django 4.2 on 2023-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_inbound_product_inbound_code_inbound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='price_inbound',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
