# Generated by Django 4.2 on 2023-04-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_inbound_price_inbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_outbound', models.CharField(max_length=20)),
                ('quantity_outbound', models.IntegerField(default=0)),
                ('date_outbound', models.DateField(auto_now_add=True)),
                ('price_outbound', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
            ],
            options={
                'db_table': 'outbound',
            },
        ),
    ]
